global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'java-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.containers.internal:8081']

  - job_name: 'go-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.containers.internal:8080']

  - job_name: 'python-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.containers.internal:8082']
